[build]
  publish = "web"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.pck"
  [headers.values]
    Content-Type = "application/octet-stream"
